let topoData = {
  code: 100,
  msg: "执行成功",
  content: {
    nodes: [
      {
        type: 5,
        typeDescription: "客户",
        id: "Customer-node1",
        name: "腾讯",
        depth: 0,
        data: {
          id: "node1",
          name: "腾讯",
          custownerId: 0,
          level: 0,
          status: 0,
          createTime: "0001-01-01T00:00:00",
          source: 0,
          linkNodeType: 5
        }
      },
      {
        type: 1,
        typeDescription: "客户设备",
        id: "CustomerDevice-node2",
        name: "IBM服务器",
        depth: 0,
        data: {
          nodeId: 0,
          deviceName: "IBM服务器",
          deviceStatus: 0,
          categoryId: 0,
          power: 0.0,
          powerText: 0.0,
          weight: 0.0,
          height: 0,
          heightPosition: 0,
          onRack: 0,
          businessStatus: 0,
          linkNodeType: 1,
          monitor: 0,
          typeId: 0,
          resStatus: 0,
          resCategory: 4,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          resId: "node2",
          register: 0,
          status: 0,
          source: 0
        }
      },
      {
        type: 7,
        typeDescription: "ODF/DDF模块",
        id: "OdfDdfModel-node3",
        name: "ODF1-1",
        depth: 0,
        data: {
          id: "node3",
          name: "ODF1-1",
          portNum: 0,
          location: 0,
          height: 0,
          linkNodeType: 7,
          resStatus: 0,
          resCategory: 170,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          nodeId: 0,
          register: 0,
          status: 0,
          source: 0
        }
      },
      {
        type: 7,
        typeDescription: "ODF/DDF模块",
        id: "OdfDdfModel-node4",
        name: "ODF2",
        depth: 0,
        data: {
          id: "node4",
          name: "ODF2",
          portNum: 0,
          location: 0,
          height: 0,
          linkNodeType: 7,
          resStatus: 0,
          resCategory: 170,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          nodeId: 0,
          register: 0,
          status: 0,
          source: 0
        }
      },
      {
        type: 6,
        typeDescription: "网络设备",
        id: "NetDevice-node5",
        name: "网络设备1",
        depth: 0,
        data: {
          ports: {},
          cpus: {},
          targetCategory: 0,
          height: 0,
          location: 0,
          power: 0.0,
          weight: 0.0,
          address: 0,
          layer: 2,
          autoBackup: false,
          portNum: 0,
          compareTypeID: 0,
          portCount: 0,
          portList: [],
          totalCPU: {
            index: 0,
            clock: 0.0,
            rate: 0,
            per1: 0,
            per5: 0
          },
          cpuList: [],
          physicalMemory: {
            descr: "",
            size: 0,
            used: 0,
            free: 0,
            lFree: 0,
            fail: 0,
            index: -1
          },
          hasSlot: false,
          slotCount: 0,
          linkNodeUuid: "node5",
          linkNodeType: 6,
          linkNodeName: "网络设备1",
          monitor: 0,
          deviceId: "node5",
          deviceName: "网络设备1",
          deviceVendorId: 0,
          categoryId: 0,
          typeId: 0,
          resStatus: 0,
          resCategory: 3,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          resId: "node5",
          resName: "网络设备1",
          nodeId: 0,
          register: 0,
          editable: false,
          status: 0,
          source: 0,
          properties: {},
          attCount: 0
        }
      },
      {
        type: 6,
        typeDescription: "网络设备",
        id: "NetDevice-node6",
        name: "网络设备2",
        depth: 0,
        data: {
          ports: {},
          cpus: {},
          targetCategory: 0,
          height: 0,
          location: 0,
          power: 0.0,
          weight: 0.0,
          address: 0,
          layer: 2,
          autoBackup: false,
          portNum: 0,
          compareTypeID: 0,
          portCount: 0,
          portList: [],
          totalCPU: {
            index: 0,
            clock: 0.0,
            rate: 0,
            per1: 0,
            per5: 0
          },
          cpuList: [],
          physicalMemory: {
            descr: "",
            size: 0,
            used: 0,
            free: 0,
            lFree: 0,
            fail: 0,
            index: -1
          },
          hasSlot: false,
          slotCount: 0,
          linkNodeUuid: "node6",
          linkNodeType: 6,
          linkNodeName: "网络设备2",
          monitor: 0,
          deviceId: "node6",
          deviceName: "网络设备2",
          deviceVendorId: 0,
          categoryId: 0,
          typeId: 0,
          resStatus: 0,
          resCategory: 3,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          resId: "node6",
          resName: "网络设备2",
          nodeId: 0,
          register: 0,
          editable: false,
          status: 0,
          source: 0,
          properties: {},
          attCount: 0
        }
      },
      {
        type: 6,
        typeDescription: "网络设备",
        id: "NetDevice-node7",
        name: "汇聚",
        depth: 0,
        data: {
          ports: {},
          cpus: {},
          targetCategory: 0,
          height: 0,
          location: 0,
          power: 0.0,
          weight: 0.0,
          address: 0,
          layer: 2,
          autoBackup: false,
          portNum: 0,
          compareTypeID: 0,
          portCount: 0,
          portList: [],
          totalCPU: {
            index: 0,
            clock: 0.0,
            rate: 0,
            per1: 0,
            per5: 0
          },
          cpuList: [],
          physicalMemory: {
            descr: "",
            size: 0,
            used: 0,
            free: 0,
            lFree: 0,
            fail: 0,
            index: -1
          },
          hasSlot: false,
          slotCount: 0,
          linkNodeUuid: "node7",
          linkNodeType: 6,
          linkNodeName: "汇聚",
          monitor: 0,
          deviceId: "node7",
          deviceName: "汇聚",
          deviceVendorId: 0,
          categoryId: 0,
          typeId: 0,
          resStatus: 0,
          resCategory: 3,
          createTimeUtc: 0,
          createTime: "0001-01-01T00:00:00",
          resId: "node7",
          resName: "汇聚",
          nodeId: 0,
          register: 0,
          editable: false,
          status: 0,
          source: 0,
          properties: {},
          attCount: 0
        }
      }
    ],
    edges: [
      {
        source: "Customer-node1",
        target: "CustomerDevice-node2"
      },
      {
        source: "CustomerDevice-node2",
        target: "OdfDdfModel-node3"
      },
      {
        source: "OdfDdfModel-node3",
        target: "OdfDdfModel-node4"
      },
      {
        source: "OdfDdfModel-node4",
        target: "NetDevice-node6"
      },
      {
        source: "NetDevice-node6",
        target: "NetDevice-node7"
      },
      {
        source: "CustomerDevice-node2",
        target: "NetDevice-node5"
      },
      {
        source: "NetDevice-node5",
        target: "NetDevice-node6"
      }
    ]
  }
};
